'use strict';
const tents=window.TENTS;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=[['category','Type'],['areaText','Area'],['size','Dimensions'],['people','Occupants'],['frame','Frame'],['cover','Cover / glazing'],['costPerSqm','Reference / m²'],['costTotal','Price reference'],['costAreaBasis','Cost area basis']];
let shown=tents,view='photos',tableSort=null,descending=false,activeTent=null,activePhotos=[],activePhoto=0,opener=null;
function spec(k,v){return `<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`;}
function imageButton(d,p,i,kind='source'){return `<figure class="photo"><button data-gallery="${d.id}" data-photo="${i}" data-gallery-kind="${kind}" aria-label="Open ${esc(d.name)}: ${esc(p.label)}"><img src="${esc(p.src)}" alt="${esc(p.alt||d.name+' — '+p.label)}" loading="lazy" decoding="async"></button><figcaption><span>${esc(p.label)}</span><span>${String(i+1).padStart(2,'0')}</span></figcaption></figure>`;}
function priceHeading(d){const amount=d.costBestTotal==null?'Quote required':`≈ €${d.costLowTotal.toLocaleString('en-IE')}${d.costLowTotal!==d.costHighTotal?'–'+d.costHighTotal.toLocaleString('en-IE'):''}`;return `${d.costKind==='quote'?'':`<span class="cost-label">${esc(d.costLabel)}</span>`}${amount}<small>${esc(d.costQualification)}</small>`;}
function costNotes(d){const priced=d.costBestTotal!=null;return `<div class="cost-method"><p><strong>${esc(d.costLabel)}.</strong> ${esc(d.costScope)}.</p><p>${esc((d.costDifference||d.costConfidence).replace(/[.]+$/,''))}.</p>${d.costDifference?`<p>${esc(d.costConfidence.replace(/[.]+$/,''))}.</p>`:''}${priced?`<p>Advertised comparison or kit price, before freight, taxes, foundations and installation. ${d.costArea?'Per-m² figure uses '+d.costArea.toFixed(1)+' m²; see the area basis above.':'Sizes vary, so no per-m² figure is shown.'}</p><p class="estimate-source">Converted using <a href="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.ff.html" target="_blank" rel="noopener">ECB reference rates, 2 October 2026</a>; rounded to euros.</p>`:''}${d.costSources.length?`<p class="estimate-source">${d.costKind==='listed'?'Supplier':'Chinese price references'}: ${d.costSources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)}</a>`).join(' · ')}.</p>`:''}</div>`;}
function supplierContact(d){if(!d.supplier)return '';const m=d.supplier;return `<section class="supplier-contact" aria-label="Possible manufacturer"><h3>${esc(m.heading||'Possible manufacturer: '+m.company)}</h3><p>${esc(m.contact)} · <a href="mailto:${esc(m.email)}">${esc(m.email)}</a></p><p>${esc(m.response)}</p><small>${esc(m.status)}. ${esc(m.provenance)}</small></section>`;}
function gardenViews(d){if(!d.visualizations?.length)return '';return `<section class="garden-views" aria-label="${esc(d.name)} Garden visualizations"><h3>At the Garden</h3><p class="visualization-scale">${esc(d.visualizationScale)}</p><div class="gallery">${d.visualizations.map((p,i)=>imageButton(d,p,i,'visualization')).join('')}</div><p class="visualization-note">AI-generated views inspired by <a href="https://thegarden.pt/" target="_blank" rel="noopener">the Garden’s woodland</a>; illustrative scale, with dimensions above.</p></section>`;}
function article(d){return `<article id="${d.id}"><div class="product-head"><div><h2><span class="number">${d.number}</span>${esc(d.name)}</h2></div><p class="colour cost-heading">${priceHeading(d)}</p></div><p class="product-summary">${esc(d.summary)}</p><div class="gallery">${d.images.slice(0,3).map((p,i)=>imageButton(d,p,i)).join('')}</div>${gardenViews(d)}<dl class="details">${[[d.costKind==='listed'?'Kit / m²':'Reference / m²',d.costPerSqm],[d.costKind==='listed'?'Kit price':'Price reference',d.costTotal],['Cost area basis',d.costAreaBasis],['Dimensions',d.size],['Occupants',d.people],['Frame',d.frame],['Cover / glazing',d.cover],['Area',d.areaText]].map(([k,v])=>spec(k,v)).join('')}</dl>${supplierContact(d)}<details class="construction"><summary>Details &amp; sources</summary><div class="construction-body">${costNotes(d)}<ul>${d.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><dl>${Object.entries(d.extras).map(([k,v])=>spec(k,v)).join('')}</dl><div class="source-notes"><ul>${d.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></div></div></details><div class="product-actions"><button class="gallery-link" data-gallery="${d.id}" data-photo="0">All images <span>${d.images.length}</span></button><div class="source-links">${(d.mockups||[]).map(m=>`<a class="maker-link" href="${esc(m.url)}" target="_blank" rel="noopener">${esc(m.label)}</a>`).join('')}${d.videos.map((url,i)=>`<a class="maker-link" href="${esc(url.replace('/embed/','/watch?v='))}" target="_blank" rel="noopener">Product video${d.videos.length>1?' '+(i+1):''}</a>`).join('')}<a class="maker-link" href="${esc(d.source)}" target="_blank" rel="noopener">${esc(d.sourceLabel||"Manufacturer’s details")}</a></div></div></article>`;}
function compareCost(x,y,key){if(x[key]==null)return y[key]==null?0:(descending?-1:1);if(y[key]==null)return descending?1:-1;return x[key]-y[key];}
function sortRecords(list){let a=[...list];if(tableSort){a.sort((x,y)=>compare(x,y,tableSort)*(descending?-1:1));}else if($('sort').value==='area'){a.sort((x,y)=>(y.area??-1)-(x.area??-1));}else if($('sort').value==='cost'){a.sort((x,y)=>(x.costBestRate??Infinity)-(y.costBestRate??Infinity));}else if($('sort').value==='name'){a.sort((x,y)=>x.name.localeCompare(y.name));}return a;}
function compare(x,y,key){if(key==='costPerSqm')return compareCost(x,y,'costBestRate');if(key==='costTotal')return compareCost(x,y,descending?'costHighTotal':'costLowTotal');if(key==='areaText'){if(x.area==null)return y.area==null?0:(descending?-1:1);if(y.area==null)return descending?1:-1;return x.area-y.area;}return String(x[key]).localeCompare(String(y[key]),undefined,{numeric:true});}
function render(){const term=$('search').value.trim().toLowerCase(),category=$('category').value;shown=sortRecords(tents.filter(d=>(category==='all'||d.category===category)&&JSON.stringify([d.name,d.category,d.summary,d.size,d.people,d.frame,d.cover,d.areaText,d.extras,d.features,d.notes,d.supplier]).toLowerCase().includes(term)));$('clear-search').hidden=!term;$('products').innerHTML=shown.map(article).join('');$('empty-state').hidden=shown.length>0;$('results-status').textContent=`${shown.length} of ${tents.length} models · ${shown.reduce((n,d)=>n+d.images.length,0)} source images · ${shown.reduce((n,d)=>n+(d.visualizations?.length||0),0)} visualizations`;$('index').innerHTML=shown.map((d,i)=>`${i===0||shown[i-1].category!==d.category?`<p class="index-category">${esc(d.category)}</p>`:''}<a href="#${d.id}" data-jump="${d.id}"><small>${d.number}</small><span>${esc(d.name)}</span></a>`).join('');renderTable();}
function renderTable(){const key=$('compare-field').value||'areaText';$('table-head').innerHTML='<tr>'+[['name','Model'],...fields].map(([k,label])=>`<th scope="col" data-col="${k}" ${k===key?'class="selected-metric"':''} aria-sort="${tableSort===k?(descending?'descending':'ascending'):'none'}"><button data-sort="${k}">${label} <span aria-hidden="true">↕</span></button></th>`).join('')+'</tr>';$('table-body').innerHTML=shown.map(d=>`<tr><td><button class="table-boot" data-show="${d.id}"><img src="${esc(d.images[0].src)}" alt="" loading="lazy"><span><small>${esc(d.category)}</small>${esc(d.name)}</span></button></td>${fields.map(([k])=>`<td data-col="${k}" ${k===key?'class="selected-metric"':''}>${esc(d[k])}</td>`).join('')}</tr>`).join('');}
function setView(v){view=v;document.body.classList.toggle('table-mode',v==='table');$('products').hidden=v==='table';$('table-panel').hidden=v!=='table';$('photo-view').setAttribute('aria-pressed',String(v==='photos'));$('table-view').setAttribute('aria-pressed',String(v==='table'));}
function openGallery(id,i,button,kind='source'){activeTent=tents.find(d=>d.id===id);activePhotos=kind==='visualization'?activeTent.visualizations:activeTent.images;activePhoto=i;opener=button;$('viewer-title').textContent=activeTent.name+(kind==='visualization'?' · At the Garden':'');$('thumbs').innerHTML=activePhotos.map((p,n)=>`<button data-thumb="${n}" aria-label="Image ${n+1}"><img src="${esc(p.src)}" alt="" loading="lazy"></button>`).join('');showPhoto();$('viewer').showModal();document.body.classList.add('modal-open');$('close').focus();}
function showPhoto(){const p=activePhotos[activePhoto];$('full-image').src=p.src;$('full-image').alt=p.alt||activeTent.name+' — '+p.label;$('photo-label').textContent=p.label+' · '+(p.credit||activeTent.imageCredit||'manufacturer image');$('counter').textContent=`${activePhoto+1} / ${activePhotos.length}`;for(const b of $('thumbs').children){b.setAttribute('aria-current',String(Number(b.dataset.thumb)===activePhoto));}const selected=$('thumbs').children[activePhoto];selected?.scrollIntoView({block:'nearest',inline:'nearest'});}
function step(n){activePhoto=(activePhoto+n+activePhotos.length)%activePhotos.length;showPhoto();}
$('photo-view').onclick=()=>setView('photos');$('table-view').onclick=()=>setView('table');$('search').oninput=render;$('category').onchange=render;$('sort').onchange=()=>{tableSort=null;render();};$('clear-search').onclick=()=>{$('search').value='';render();$('search').focus();};$('compare-field').innerHTML=fields.map(([k,label])=>`<option value="${k}">${label}</option>`).join('');$('compare-field').value='areaText';$('compare-field').onchange=renderTable;
document.addEventListener('click',e=>{const button=e.target.closest('button');if(button?.dataset.gallery)openGallery(button.dataset.gallery,Number(button.dataset.photo),button,button.dataset.galleryKind);if(button?.dataset.thumb){activePhoto=Number(button.dataset.thumb);showPhoto();}if(button?.dataset.sort){descending=tableSort===button.dataset.sort?!descending:false;tableSort=button.dataset.sort;render();}if(button?.dataset.show){setView('photos');const target=document.getElementById(button.dataset.show);target.scrollIntoView({block:'start'});target.querySelector('.gallery-link').focus({preventScroll:true});}const a=e.target.closest('[data-jump]');if(a){for(const n of $('index').querySelectorAll('a'))n.removeAttribute('aria-current');a.setAttribute('aria-current','true');}});
$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('close').onclick=()=>$('viewer').close();$('viewer').addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus({preventScroll:true});});$('viewer').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}if(e.key==='ArrowRight'){e.preventDefault();step(1);}});let touchStart=null;$('full-image').addEventListener('touchstart',e=>touchStart=e.changedTouches[0].clientX,{passive:true});$('full-image').addEventListener('touchend',e=>{if(touchStart!==null){const dx=e.changedTouches[0].clientX-touchStart;if(Math.abs(dx)>45)step(dx<0?1:-1);touchStart=null;}},{passive:true});
$('asset-count').textContent=`${tents.length} models · ${tents.reduce((n,d)=>n+d.images.length,0)} source images · ${tents.reduce((n,d)=>n+(d.visualizations?.length||0),0)} AI visualizations`;render();
